[features]
seeds = false
skip-lint = false
[programs.devnet]
news = "GU9hKq1tHquQr42P9v6odWWW5cFrW55vcxS3VLrfQzjR"
campaign = "Cm54nANsmCodcqRgajkm7NHeZisRYPyRQnBRcEBFZ1s6"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "/home/messi/dev-wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
