[features]
seeds = false
skip-lint = false
[programs.devnet]
degen_news = "8HZqEJqtG49XeXHY4277jv6VQsMz9rwLq2z4tZYR8DQv"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "/home/messi/dev-wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
